# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)




tipodocs = [
	    {nombre: "Cedula de Ciudadania"},
	    {nombre: "Tarjeta de Identidad"}, 
	    {nombre: "Registro Civil"},
	    {nombre: "Cedula de Extranjeria"}
	    
	]

tipodocs.each do | tipodoc |

	Tipodoc.create(tipodoc) unless Tipodoc.exists?(tipodoc)
		
end


personalinvolucrados = [
	    {nombre: "Funcionario"},
	    {nombre: "Contratista"}, 
	    {nombre: "Visitante"}
	    
	    
	]

personalinvolucrados.each do | personalinvolucrado |

	Personalinvolucrado.create(personalinvolucrado) unless Personalinvolucrado.exists?(personalinvolucrado)
		
end


centros = [
	    {nombre: " Centro Tecnológico del Mobiliario"},
	    {nombre: "Centro de Formación en Diseño Cofección y Moda"}, 
	    {nombre: "Centro de Diseño y Manufactura del Cuero"}
	
	    
	]

centros.each do | centro |

	Centro.create(centro) unless Centro.exists?(centro)
		
end


tipo_salidas = [{nombre: "Pedagogica"}, {nombre: "Recreativa"}, {nombre: "Cultural"}, {nombre: "Social"}, {nombre: "Sociocultural"}]

tipo_salidas.each do | tipo_salida |

	TipoSalida.where(tipo_salida).first_or_create		
end


tiporiesgos = [{nombre: "Clase I, de Riesgo Mínimo"}, {nombre: "Clase II, de Riesgo Bajo"}, {nombre: "Clase III, de Riesgo Medio"}, {nombre: "Clase IV, de Riesgo Alto"}, {nombre: "Clase V, de Riesgo Máximo"}]

tiporiesgos.each do | tiporiesgo |

	Tiporiesgo.where(tiporiesgo ).first_or_create		
end


tipoincapacidads = [{nombre: "Incapacidad Laboral Transitoria"}, {nombre: "Invalidez Provisional"}, {nombre: "Invalidez Permanente"}, {nombre: "Incapacidad Permanente Parcial"}, {nombre: "Incapacidad Permanente Total"}, {nombre: "Incapacidad Permanente Absoluta"}, {nombre: "Gran Invalidez"}]

tipoincapacidads.each do | tipoincapacidad |

	Tipoincapacidad.where(tipoincapacidad).first_or_create		
end


tipoenfermedads = [{nombre: "Enfermedades agudas"}, {nombre: "Enfermedades Cronicas"}, {nombre: "Enfermedades contagiosas"}, {nombre: "Enfermedades no contagiosas"}, {nombre: "Enfermedades endémicas"}, {nombre: "Enfermedades esporádicas"}, {nombre: "Enfermedades epidémicas"}]

tipoenfermedads.each do | tipoenfermedad |

	Tipoenfermedad.where(tipoenfermedad).first_or_create		
end


tipoincidentes = [{nombre: "Ordinarios"}, {nombre: "Especiales"}, {nombre: "Conexos"}, {nombre: "Inconexos"}]

tipoincidentes.each do | tipoincidente |

	Tipoincidente.where(tipoincidente).first_or_create		
end






municipios=[{nombre:"Santafé de Bogotá"},{nombre:"Puerto Nariño"},{nombre:"Leticia"},
{nombre:"Medellín"},{nombre:"Abejorral"},{nombre:"Abriaqui"},{nombre:"Alejandría"},{nombre:"Amagá"},
{nombre:"Amalfi"},{nombre:"Andes"},{nombre:"Angelópolis"},{nombre:"Angostura"},{nombre:"Anorí"},
{nombre:"Anzá"},{nombre:"Apartadó"},{nombre:"Arboletes"},{nombre:"Argelia"},{nombre:"Armenia"},
{nombre:"Barbosa"},{nombre:"Belmira"},{nombre:"Bello"},{nombre:"Betania"},{nombre:"Betulia"},{nombre:"Bolívar"},
{nombre:"Briseño"},{nombre:"Buriticá"},{nombre:"Cáceres"},{nombre:"Caicedo"},{nombre:"Caldas"},
{nombre:"Campamento"},{nombre:"Cañasgordas"},{nombre:"Caracolí"},{nombre:"Caramanta"},{nombre:"Carepa"},
{nombre:"Carmen de Viboral"},{nombre:"Carolina"},{nombre:"Caucasia"},{nombre:"Chigorodó"},{nombre:"Cisneros"},
{nombre:"Cocorná"},{nombre:"Concepción"},{nombre:"Concordia"},{nombre:"Copacabana"},{nombre:"Dabeiba"},
{nombre:"Don Matías"},{nombre:"Ebéjico"},{nombre:"El Bagre"},{nombre:"Entrerríos"},{nombre:"Envigado"},
{nombre:"Fredonia"},{nombre:"Frontino"},{nombre:"Giraldo"},{nombre:"Girardota"},{nombre:"Gómez Plata"},
{nombre:"Granada"},{nombre:"Guadalupe"},{nombre:"Guarne"},{nombre:"Guatapé"},{nombre:"Heliconia"},
{nombre:"Hispania"},{nombre:"Itagüí"},{nombre:"Ituango"},{nombre:"Jardín"},{nombre:"Jericó"},{nombre:"La Ceja"},
{nombre:"La Estrella"},{nombre:"La Pintada"},{nombre:"La Unión"},{nombre:"Liborina"},{nombre:"Maceo"},{nombre:"Marinilla"},
{nombre:"Montebello"},{nombre:"Murindó"},{nombre:"Mutatá"},{nombre:"Nariño"},{nombre:"Necoclí"},{nombre:"Nechí"},
{nombre:"Olaya"},{nombre:"Peñol"},{nombre:"Peque"},{nombre:"Pueblorrico"},{nombre:"Puerto Berrío"},{nombre:"Puerto Nare"},
{nombre:"Puerto Triunfo"},{nombre:"Remedios"},{nombre:"Retiro"},{nombre:"Rionegro"},{nombre:"Sabanalarga"},
{nombre:"Sabaneta"},{nombre:"Salgar"},{nombre:"San Andrés"},{nombre:"San Carlos"},{nombre:"San francisco"},
{nombre:"San Jerónimo"},{nombre:"San José de Montaña"},{nombre:"San Juan de Urabá"},{nombre:"San Luis"},
{nombre:"San Pedro"},{nombre:"San Pedro de Urabá"},{nombre:"San Rafael"},{nombre:"San Roque"},{nombre:"San Vicente"},
{nombre:"Santa Bárbara"},{nombre:"Santa Rosa de Osos"},{nombre:"Santo Domingo"},{nombre:"Santuario"},
{nombre:"Segovia"},{nombre:"Sonsón"},{nombre:"Sopetrán"},{nombre:"Támesis"},{nombre:"Tarazá"},{nombre:"Tarso"},
{nombre:"Titiribí"},{nombre:"Toledo"},{nombre:"Turbo"},{nombre:"Uramita"},{nombre:"Urrao"},{nombre:"Valdivia"},
{nombre:"Valparaíso"},{nombre:"Vegachí"},{nombre:"Venecia"},{nombre:"Vigía del Fuerte"},{nombre:"Yalí"},
{nombre:"Yarumal"},{nombre:"Yolombó"},{nombre:"Yondó (Casabe)"},{nombre:"Zaragoza"},{nombre:"Arauca"},
{nombre:"Arauquita"},{nombre:"Cravo Norte"},{nombre:"Fortul"},{nombre:"Puerto Rondón"},{nombre:"Fortul"},
{nombre:"Saravena"},{nombre:"Tame"},{nombre:"Barranquilla"},{nombre:"Baranoa"},{nombre:"Campo de la Cruz"},
{nombre:"Candelaria"},{nombre:"Galapa"},{nombre:"Juan de Acosta"},{nombre:"Luruaco"},{nombre:"Malambo"},
{nombre:"Manatí"},{nombre:"Palmar de Varela"},{nombre:"Piojó"},{nombre:"Polonuevo"},{nombre:"Ponedera"},
{nombre:"Puerto Colombia"},{nombre:"Repelón"},{nombre:"Sabanagrande"},{nombre:"Sabanalarga"},{nombre:"Santa Lucía"},
{nombre:"Santo Tomás"},{nombre:"Soledad"},{nombre:"Suán"},{nombre:"Tubará"},{nombre:"Usiacurí"},
{nombre:"Cartagena"},{nombre:"Achí"},{nombre:"Altos del Rosario"},{nombre:"Arenal"},{nombre:"Arjona"},
{nombre:"Arroyohondo"},{nombre:"Barranco de Loba"},{nombre:"Calamar"},{nombre:"Cantagallo"},{nombre:"Cicuto"},
{nombre:"Córdoba"},{nombre:"Clemencia"},{nombre:"El Carmen de Bolívar"},{nombre:"El Guamo"},{nombre:"El Peñón"},
{nombre:"Hatillo de Loba"},{nombre:"Magangue"},{nombre:"Mahates"},{nombre:"Margarita"},{nombre:"María la Baja"},
{nombre:"Montecristo"},{nombre:"Mompós"},{nombre:"Morales"},{nombre:"Pinillos"},{nombre:"Regidor"},
{nombre:"Río Viejo"},{nombre:"San Cristóbal"},{nombre:"San Estanislao"},{nombre:"San Fernando"},{nombre:"San Jacinto"},
{nombre:"San Jacinto del Cauca"},{nombre:"San Juan Nepomuceno"},{nombre:"San Martín de Loba"},{nombre:"San Pablo"},
{nombre:"Santa Catalina"},{nombre:"Santa Rosa"},{nombre:"Santa Rosa del Sur"},{nombre:"Simití"},{nombre:"Soplaviento"},
{nombre:"Talaigua Nuevo"},{nombre:"Tiquisio (Puerto Rico)"},{nombre:"Turbaco"},{nombre:"Turbaná"},{nombre:"Villanueva"},
{nombre:"Zambrano"},{nombre:"Tunja"},{nombre:"Almeida"},{nombre:"Aquitania"},{nombre:"Arcabuco"},{nombre:"Belén"},
{nombre:"Berbeo"},{nombre:"Beteitiva"},{nombre:"Boavita"},{nombre:"Boyacá"},{nombre:"Briseño"},{nombre:"Buenavista"},
{nombre:"Busbanzá"},{nombre:"Caldas"},{nombre:"Campohermoso"},{nombre:"Cerinza"},{nombre:"Chinavita"},{nombre:"Chiquinquirá"},
{nombre:"Chiscas"},{nombre:"Chita"},{nombre:"Chitaranque"},{nombre:"Chivatá"},{nombre:"Ciénaga"},{nombre:"Cómbita"},
{nombre:"Coper"},{nombre:"Corrales"},{nombre:"Covarachia"},{nombre:"Cubar"},{nombre:"Cucaita"},{nombre:"Cuitiva"},
{nombre:"Chíquiza"},{nombre:"Chivor"},{nombre:"Duitama"},{nombre:"El Cocuy"},{nombre:"El Espino"},{nombre:"Firavitoba"},
{nombre:"Floresta"},{nombre:"Gachantivá"},{nombre:"Gámeza"},{nombre:"Garagoa"},{nombre:"Guacamayas"},{nombre:"Guateque"},
{nombre:"Guayatá"},{nombre:"Guicán"},{nombre:"Iza"},{nombre:"Jenesano"},{nombre:"Jericó"},{nombre:"Labranzagrande"},
{nombre:"La Capilla"},{nombre:"La Victoria"},{nombre:"La Ubita"},{nombre:"Villa de Leyva"},{nombre:"Macanal"},
{nombre:"Maripí"},{nombre:"Miraflores"},{nombre:"Mongua"},{nombre:"Monguí"},{nombre:"Moniquirá"},{nombre:"Motavita"},
{nombre:"Muzo"},{nombre:"Nobsa"},{nombre:"Nuevo Colón"},{nombre:"Oicatá"},{nombre:"Otanche"},{nombre:"Pachavita"},
{nombre:"Páez"},{nombre:"Paipa"},{nombre:"Pajarito"},{nombre:"Panqueba"},{nombre:"Pauna"},{nombre:"Paya"},
{nombre:"Paz de Río"},{nombre:"Pesca"},{nombre:"Pisva"},{nombre:"Puerto Boyacá"},{nombre:"Quípama"},{nombre:"Ramiquirí"},
{nombre:"Ráquira"},{nombre:"Rondón"},{nombre:"Saboyá"},{nombre:"Sáchica"},{nombre:"Samacá"},{nombre:"San Eduardo"},
{nombre:"San José de Pare"},{nombre:"San Luis de Gaceno"},{nombre:"San Mateo"},{nombre:"San Miguel de Sema"},
{nombre:"San Pablo de Borbur"},{nombre:"Santana"},{nombre:"Santa María"},{nombre:"Santa Rosa de Viterbo"},
{nombre:"Santa Sofía"},{nombre:"Sativanorte"},{nombre:"Sativasur"},{nombre:"Siachoque"},{nombre:"Soatá"},
{nombre:"Socotá"},{nombre:"Socha"},{nombre:"Sogamoso"},{nombre:"Somondoco"},{nombre:"Sora"},{nombre:"Sotaquirá"},
{nombre:"Soracá"},{nombre:"Susacón"},{nombre:"Sutamarchán"},{nombre:"Sutatenza"},{nombre:"Tasco"},{nombre:"Tenza"},
{nombre:"Tibaná"},{nombre:"Tibasosa"},{nombre:"Tinjacá"},{nombre:"Tipacoque"},{nombre:"Toca"},{nombre:"Toguí"},
{nombre:"Tópaga"},{nombre:"Tota"},{nombre:"Tunungua"},{nombre:"Turmequé"},{nombre:"Tuta"},{nombre:"Tutazá"},
{nombre:"Úmbita"},{nombre:"Ventaquemada"},{nombre:"Viracachá"},{nombre:"Zetaquirá"},{nombre:"Manizales"},
{nombre:"Aguadas"},{nombre:"Anserma"},{nombre:"Aranzazu"},{nombre:"Belalcázar"},{nombre:"Chinchina"},
{nombre:"Filadelfia"},{nombre:"La Dorada"},{nombre:"La Merced"},{nombre:"Manzanares"},{nombre:"Marmato"},
{nombre:"Marquetalia"},{nombre:"Marulanda"},{nombre:"Neira"},{nombre:"Pácora"},{nombre:"Palestina"},
{nombre:"Pensilvania"},{nombre:"Riosucio"},{nombre:"Risaralda"},{nombre:"Salamina"},{nombre:"Samaná"},{nombre:"San José"},
{nombre:"Supía"},{nombre:"Victoria"},{nombre:"Villamaría"},{nombre:"Viterbo"},{nombre:"Florencia"},
{nombre:"Albania"},{nombre:"Belén de los Andaquíes"},{nombre:"Cartagena del Chairá"},{nombre:"Curillo"},
{nombre:"El Doncello"},{nombre:"El Paujil"},{nombre:"La Montañita"},{nombre:"Milán"},{nombre:"Morelia"},
{nombre:"Puerto Rico"},{nombre:"San José del Fragua"},{nombre:"San Vicente del Caguán"},{nombre:"Solano"},
{nombre:"Solita"},{nombre:"Valparaíso"},{nombre:"Yopal"},{nombre:"Aguazul"},{nombre:"Chameza"},
{nombre:"Hato Corozal"},{nombre:"La Salina"},{nombre:"Maní"},{nombre:"Monterrey"},{nombre:"Nunchía"},
{nombre:"Orocué"},{nombre:"Paz de Ariporo"},{nombre:"Pore"},{nombre:"Recetor"},{nombre:"Sabalarga"},
{nombre:"Sácama"},{nombre:"San Luis de Palenque"},{nombre:"Támara"},{nombre:"Tauramena"},{nombre:"Trinidad"},
{nombre:"Villanueva"},
{nombre:"Popayán"},
{nombre:"Almaguer"},
{nombre:"Argelia"},
{nombre:"Balboa"},
{nombre:"Bolívar"},
{nombre:"Buenos Aires"},
{nombre:"Cajibío"},
{nombre:"Caldono"},
{nombre:"Caloto"},
{nombre:"Corinto"},
{nombre:"El Tambo"},
{nombre:"Florencia"},
{nombre:"Guapi"},
{nombre:"Inzá"},
{nombre:"Jambaló"},
{nombre:"La Sierra"},
{nombre:"La Vega"},
{nombre:"López (Micay)"},
{nombre:"Mercaderes"},
{nombre:"Miranda"},
{nombre:"Morales"},
{nombre:"Padilla"},
{nombre:"Páez (Belalcazar)"},
{nombre:"Patía (El Bordo)"},
{nombre:"Piamonte"},
{nombre:"Piendamó"},
{nombre:"Puerto Tejada"},
{nombre:"Puracé (Coconuco)"},
{nombre:"Rosas"},
{nombre:"San Sebastián"},
{nombre:"Santander de Quilichao"},
{nombre:"Santa Rosa"},
{nombre:"Silvia"},
{nombre:"Sotará (Paispamba)"},
{nombre:"Suárez"},
{nombre:"Timbío"},
{nombre:"Timbiquí"},
{nombre:"Toribío"},
{nombre:"Totoro"},
{nombre:"Valledupar"},
{nombre:"Aguachica"},
{nombre:"Agustín Codazzi"},
{nombre:"Astrea"},
{nombre:"Becerril"},
{nombre:"Bosconia"},
{nombre:"Chimichagua"},
{nombre:"Chiriguaná"},
{nombre:"Curumaní"},
{nombre:"El Copey"},
{nombre:"El Paso"},
{nombre:"Gamarra"},
{nombre:"González"},
{nombre:"La Gloria"},
{nombre:"La Jagua de Ibirico"},
{nombre:"Manaure Balcón Cesar"},
{nombre:"Pailitas"},
{nombre:"Pelaya"},
{nombre:"Pueblo Bello"},
{nombre:"Río de Oro"},
{nombre:"La Paz (Robles)"},
{nombre:"San Alberto"},
{nombre:"San Diego"},
{nombre:"San Martín"},
{nombre:"Tamalameque"},
{nombre:"Montería"},
{nombre:"Ayapel"},
{nombre:"Buenavista"},
{nombre:"Canalete"},
{nombre:"Cereté"},
{nombre:"Chima"},
{nombre:"Chinú"},
{nombre:"Ciénaga de Oro"},
{nombre:"Cotorra"},
{nombre:"La Apartada (Frontera)"},
{nombre:"Lorica"},
{nombre:"Los Córdobas"},
{nombre:"Momil"},
{nombre:"Montelíbano"},
{nombre:"Monitos"},
{nombre:"Planeta Rica"},
{nombre:"Pueblo Nuevo"},
{nombre:"Puerto Escondido"},
{nombre:"Puerto Libertador"},
{nombre:"Purísima"},
{nombre:"Sahagún"},
{nombre:"San Andrés Sotavento"},
{nombre:"San Antero"},
{nombre:"San Bernardo del Viento"},
{nombre:"San Carlos"},
{nombre:"San Pelayo"},
{nombre:"Tierralta"},
{nombre:"Valencia"},
{nombre:"Agua de Dios"},
{nombre:"Albán"},
{nombre:"Anapoima"},
{nombre:"Anolaima"},
{nombre:"Arbeláez"},
{nombre:"Beltrán"},
{nombre:"Bituima"},
{nombre:"Bojacá"},
{nombre:"Cabrera"},
{nombre:"Cachipay"},
{nombre:"Cajicá"},
{nombre:"Caparrapí"},
{nombre:"Cáqueza"},
{nombre:"Carmen de Carupa"},
{nombre:"Chaguaní"},
{nombre:"Chía"},
{nombre:"Chipaque"},
{nombre:"Choachí"},
{nombre:"Chocontá"},
{nombre:"Cogua"},
{nombre:"Cota"},
{nombre:"Cucunubá"},
{nombre:"El Colegio"},
{nombre:"El Peñón"},
{nombre:"El Rosal"},
{nombre:"Facatativá"},
{nombre:"Fómeque"},
{nombre:"Fosca"},
{nombre:"Funza"},
{nombre:"Fúquene"},
{nombre:"Fusagasugá"},
{nombre:"Gachalá"},
{nombre:"Gachancipá"},
{nombre:"Gachetá"},
{nombre:"Gama"},
{nombre:"Girardot"},
{nombre:"Granada"},
{nombre:"Guachetá"},
{nombre:"Guaduas"},
{nombre:"Guasca"},
{nombre:"Guataquí"},
{nombre:"Guatavita"},
{nombre:"Guayabal de Síquima"},
{nombre:"Guayabetal"},
{nombre:"Gutiérrez"},
{nombre:"Jerusalén"},
{nombre:"Junín"},
{nombre:"La Calera"},
{nombre:"La Mesa"},
{nombre:"La Palma"},
{nombre:"La Peña"},
{nombre:"La Vega"},
{nombre:"Lenguazaque"},
{nombre:"Machetá"},
{nombre:"Madrid"},
{nombre:"Manta"},
{nombre:"Medina"},
{nombre:"Mosquera"},
{nombre:"Nariño"},
{nombre:"Nemocón"},
{nombre:"Nilo"},
{nombre:"Nimaima"},
{nombre:"Nocaima"},
{nombre:"Venecia (Ospina Pérez)"},
{nombre:"Pacho"},
{nombre:"Paime"},
{nombre:"Pandi"},
{nombre:"Paratebueno"},
{nombre:"Pasca"},
{nombre:"Puerto Salgar"},
{nombre:"Pulí"},
{nombre:"Quebradanegra"},
{nombre:"Quetame"},
{nombre:"Quipile"},
{nombre:"Rafael"},
{nombre:"Ricaurte"},
{nombre:"San Antonio de Tequendama"},
{nombre:"San Bernardo"},
{nombre:"San Cayetano"},
{nombre:"San Francisco"},
{nombre:"San Juan de Rioseco"},
{nombre:"Sasaima"},
{nombre:"Sesquilé"},
{nombre:"Sibate"},
{nombre:"Silvania"},
{nombre:"Simijaca"},
{nombre:"Soacha"},
{nombre:"Sopó"},
{nombre:"Subachoque"},
{nombre:"Suesca"},
{nombre:"Supatá"},
{nombre:"Susa"},
{nombre:"Sutatausa"},
{nombre:"Tabio"},
{nombre:"Tausa"},
{nombre:"Tena"},
{nombre:"Tenjo"},
{nombre:"Tibacuy"},
{nombre:"Tibiritá"},
{nombre:"Tocaima"},
{nombre:"Tocancipá"},
{nombre:"Topaipí"},
{nombre:"Ubalá"},
{nombre:"Ubaque"},
{nombre:"Ubaté"},
{nombre:"Une"},
{nombre:"Útica"},
{nombre:"Vergara"},
{nombre:"Vianí"},
{nombre:"Villagómez"},
{nombre:"Villapinzón"},
{nombre:"Villeta"},
{nombre:"Viotá"},
{nombre:"Yacopí"},
{nombre:"Zipacón"},
{nombre:"Zipaquirá"},
{nombre:"Quibdó"},
{nombre:"Acandí"},
{nombre:"Alto Baudó (Pie de Pato)"},
{nombre:"Atrato (Yuto)"},
{nombre:"Bagadó"},
{nombre:"Bahía Solano (Mútis)"},
{nombre:"Bajo Baudó (Pizarro)"},
{nombre:"Bojayá (Bellavista)"},
{nombre:"Cantón de San Pablo"},
{nombre:"Condoto"},
{nombre:"El Carmen"},
{nombre:"El Litoral de San Juan"},
{nombre:"Itsmina"},
{nombre:"Juradó"},
{nombre:"Lloró"},
{nombre:"Nóvita"},
{nombre:"Nuquí"},
{nombre:"Riosucio"},
{nombre:"San José del Palmar"},
{nombre:"Sipí"},
{nombre:"Tadó"},
{nombre:"Unguía"},
{nombre:"Guainía"},{nombre:"Inírida"},
{nombre:"Guaviare"},{nombre:"San José del Guaviare"},
{nombre:"Calamar"},
{nombre:"El Retorno"},
{nombre:"Miraflores"},
{nombre:"Neiva"},
{nombre:"Acevedo"},
{nombre:"Agrado"},
{nombre:"Aipe"},
{nombre:"Algeciras"},
{nombre:"Altamira"},
{nombre:"Baraya"},
{nombre:"Campoalegre"},
{nombre:"Colombia"},
{nombre:"Elías"},
{nombre:"Garzón"},
{nombre:"Gigante"},
{nombre:"Guadalupe"},
{nombre:"Hobo"},
{nombre:"Iquira"},
{nombre:"Isnos"},
{nombre:"La Argentina"},
{nombre:"La Plata"},
{nombre:"Nátaga"},
{nombre:"Oporapa"},
{nombre:"Paicol"},
{nombre:"Palermo"},
{nombre:"Palestina"},
{nombre:"Pital"},
{nombre:"Pitalito"},
{nombre:"Rivera"},
{nombre:"Saladoblanco"},
{nombre:"San Agustín"},
{nombre:"Santa María"},
{nombre:"Suazá"},
{nombre:"Tarqui"},
{nombre:"Tesalia"},
{nombre:"Tello"},
{nombre:"Teruel"},
{nombre:"Timaná"},
{nombre:"Villavieja"},
{nombre:"Yaguará"},
{nombre:"Riohacha"},
{nombre:"Barrancas"},
{nombre:"Dibulla"},
{nombre:"Distracción"},
{nombre:"El Molino"},
{nombre:"Fonseca"},
{nombre:"Hatonuevo"},
{nombre:"Maicao"},
{nombre:"Manaure"},
{nombre:"San Juan del Cesar"},
{nombre:"Uribía"},
{nombre:"Urumita"},
{nombre:"Villanueva"},
{nombre:"Santa Marta"},
{nombre:"Aracataca"},
{nombre:"Ariguaní (El Difícil)"},
{nombre:"Cerro San Antonio"},
{nombre:"Chivolo"},
{nombre:"Ciénaga"},
{nombre:"El Banco"},
{nombre:"El Piñón"},
{nombre:"El Retén"},
{nombre:"Fundación"},
{nombre:"Guamal"},
{nombre:"Pedraza"},
{nombre:"Pijiño del Carmen"},
{nombre:"Pivijay"},
{nombre:"Plato"},
{nombre:"Publoviejo"},
{nombre:"Remolino"},
{nombre:"Salamina"},
{nombre:"San Sebastián de Buenavista"},
{nombre:"San Zenón"},
{nombre:"Santa Ana"},
{nombre:"Sitionuevo"},
{nombre:"Tenerife"},
{nombre:"Meta"},{nombre:"Villavicencio"},
{nombre:"Acacias"},
{nombre:"Barranca de Upía"},
{nombre:"Cabuyaro"},
{nombre:"Castilla la Nueva"},
{nombre:"Cubarral"},
{nombre:"Cumaral"},
{nombre:"El Calvario"},
{nombre:"El Castillo"},
{nombre:"El Dorado"},
{nombre:"Fuente de Oro"},
{nombre:"Granada"},
{nombre:"Guamal"},
{nombre:"Mapiripán"},
{nombre:"Mesetas"},
{nombre:"La Macarena"},
{nombre:"La Uribe"},
{nombre:"Lejanías"},
{nombre:"Puerto Concordia"},
{nombre:"Puerto Gaitán"},
{nombre:"Puerto López"},
{nombre:"Puerto Lleras"},
{nombre:"Puerto Rico"},
{nombre:"Restrepo"},
{nombre:"San Carlos de Guaroa"},
{nombre:"San Juan de Arama"},
{nombre:"San Juanito"},
{nombre:"San Martín"},
{nombre:"Vistahermosa"},
{nombre:"Pasto"},
{nombre:"Albán (San José)"},
{nombre:"Aldana"},
{nombre:"Ancuyá"},
{nombre:"Arboleda (Berruecos)"},
{nombre:"Barbacoas"},
{nombre:"Belén"},
{nombre:"Buesaco"},
{nombre:"Colón (Génova)"},
{nombre:"Consacá"},
{nombre:"Contadero"},
{nombre:"Córdoba"},
{nombre:"Cuaspud (Carlosama)"},
{nombre:"Cumbal"},
{nombre:"Cumbitará"},
{nombre:"Chachagüi"},
{nombre:"El Charco"},
{nombre:"El Rosario"},
{nombre:"El Tablón"},
{nombre:"El Tambo"},
{nombre:"Funes"},
{nombre:"Guachucal"},
{nombre:"Guaitarilla"},
{nombre:"Gualmatán"},
{nombre:"Iles"},
{nombre:"Imúes"},
{nombre:"Ipiales"},
{nombre:"La Cruz"},
{nombre:"La Florida"},
{nombre:"La Llanada"},
{nombre:"La Tola"},
{nombre:"La Unión"},
{nombre:"Leiva"},
{nombre:"Linares"},
{nombre:"Los Andes (Sotomayor)"},
{nombre:"Magüí (Payán)"},
{nombre:"Mallama (Piedrancha)"},
{nombre:"Mosquera"},
{nombre:"Olaya"},
{nombre:"Ospina"},
{nombre:"Francisco Pizarro"},
{nombre:"Policarpa"},
{nombre:"Potosí"},
{nombre:"Providencia"},
{nombre:"Puerres"},
{nombre:"Pupiales"},
{nombre:"Ricaurte"},
{nombre:"Roberto Payán (San José)"},
{nombre:"Samaniego"},
{nombre:"Sandoná"},
{nombre:"San Bernardo"},
{nombre:"San Lorenzo"},
{nombre:"San Pablo"},
{nombre:"San Pedro de Cartago"},
{nombre:"Santa Bárbara (Iscuandé)"},
{nombre:"Santa Cruz (Guachávez)"},
{nombre:"Sapuyés"},
{nombre:"Taminango"},
{nombre:"Tangua"},
{nombre:"Tumaco"},
{nombre:"Túquerres"},
{nombre:"Yacuanquer"},
{nombre:"Cúcuta"},
{nombre:"Abrego"},
{nombre:"Arboledas"},
{nombre:"Bochalema"},
{nombre:"Bucarasica"},
{nombre:"Cácota"},
{nombre:"Cáchira"},
{nombre:"Chinácota"},
{nombre:"Chitagá"},
{nombre:"Convención"},
{nombre:"Cucutilla"},
{nombre:"Durania"},
{nombre:"El Carmen"},
{nombre:"El Tarra"},
{nombre:"El Zulia"},
{nombre:"Gramalote"},
{nombre:"Hacarí"},
{nombre:"Herrán"},
{nombre:"Labateca"},
{nombre:"La Esperanza"},
{nombre:"La Playa"},
{nombre:"Los Patios"},
{nombre:"Lourdes"},
{nombre:"Mutiscua"},
{nombre:"Ocaña"},
{nombre:"Pamplona"},
{nombre:"Pamplonita"},
{nombre:"Puerto Santander"},
{nombre:"Ragonvalia"},
{nombre:"Salazar"},
{nombre:"San Calixto"},
{nombre:"San Cayetano"},
{nombre:"Santiago"},
{nombre:"Sardinata"},
{nombre:"Silos"},
{nombre:"Teorama"},
{nombre:"Tibú"},
{nombre:"Toledo"},
{nombre:"Villacaro"},
{nombre:"Villa del Rosario"},
{nombre:"Mocoa"},
{nombre:"Colón"},
{nombre:"Orito"},
{nombre:"Puerto Asís"},
{nombre:"Puerto Caicedo"},
{nombre:"Puerto Guzmán"},
{nombre:"Puerto Leguízamo"},
{nombre:"Sibundoy"},
{nombre:"San Francisco"},
{nombre:"San Miguel"},
{nombre:"Santiago"},
{nombre:"Villa Gamuez (La Hormiga)"},
{nombre:"Villa Garzón"},
{nombre:"Quindío"},
{nombre:" Armenia"},
{nombre:"Buenavista"},
{nombre:"Calarcá"},
{nombre:"Circasia"},
{nombre:"Córdoba"},
{nombre:"Filandia"},
{nombre:"Génova"},
{nombre:"La Tebaida"},
{nombre:"Montenegro"},
{nombre:"Pijao"},
{nombre:"Quimbaya"},
{nombre:"Salento"},
{nombre:"Pereira"},
{nombre:"Apía"},
{nombre:"Balboa"},
{nombre:"Belén de Umbría"},
{nombre:"Dos Quebradas"},
{nombre:"Guática"},
{nombre:"La Celia"},
{nombre:"La Virginia"},
{nombre:"Marsella"},
{nombre:"Mistrató"},
{nombre:"Pueblo Rico"},
{nombre:"Quinchia"},
{nombre:"Santa Rosa de Cabal"},
{nombre:"Santuario"},
{nombre:"San Andrés"},
{nombre:"Providencia"},
{nombre:"Bucaramanga"},
{nombre:"Aguada"},
{nombre:"Albania"},
{nombre:"Aratoca"},
{nombre:"Barbosa"},
{nombre:"Barichara"},
{nombre:"Barrancabermeja"},
{nombre:"Betulia"},
{nombre:"Bolívar"},
{nombre:"Cabrera"},
{nombre:"California"},
{nombre:"Capitanejo"},
{nombre:"Carcasí"},
{nombre:"Cepitá"},
{nombre:"Cerrito"},
{nombre:"Charalá"},
{nombre:"Charta"},
{nombre:"Chima"},
{nombre:"Chipatá"},
{nombre:"Cimitarra"},
{nombre:"Concepción"},
{nombre:"Confines"},
{nombre:"Contratación"},
{nombre:"Coromoro"},
{nombre:"Curití"},
{nombre:"El Carmen"},
{nombre:"El Guacamayo"},
{nombre:"El Peñón"},
{nombre:"El Playón"},
{nombre:"Encino"},
{nombre:"Enciso"},
{nombre:"Florián"},
{nombre:"Floridablanca"},
{nombre:"Galán"},
{nombre:"Gámbita"},
{nombre:"Girón"},
{nombre:"Guaca"},
{nombre:"Guadalupe"},
{nombre:"Guapotá"},
{nombre:"Guavata"},
{nombre:"Guepsa"},
{nombre:"Hato"},
{nombre:"Jesús María"},
{nombre:"Jordán"},
{nombre:"La Belleza"},
{nombre:"Landázuri"},
{nombre:"La Paz"},
{nombre:"Lebrija"},
{nombre:"Los Santos"},
{nombre:"Macaravita"},
{nombre:"Málaga"},
{nombre:"Matanza"},
{nombre:"Mogotes"},
{nombre:"Molagavita"},
{nombre:"Ocamonte"},
{nombre:"Oiba"},
{nombre:"Onzága"},
{nombre:"Palmar"},
{nombre:"Palmas del Socorro"},
{nombre:"Páramo"},
{nombre:"Pie de Cuesta"},
{nombre:"Pinchote"},
{nombre:"Puente Nacional"},
{nombre:"Puerto Parra"},
{nombre:"Puerto Wilches"},
{nombre:"Rionegro"},
{nombre:"Sabana de Torres"},
{nombre:"San Andrés"},
{nombre:"San Benito"},
{nombre:"San Gil"},
{nombre:"San Joaquín"},
{nombre:"San José de Miranda"},
{nombre:"San Miguel"},
{nombre:"San Vicente de Chucurí"},
{nombre:"Santa Bárbara"},
{nombre:"Santa Helena del Opón"},
{nombre:"Simacota"},
{nombre:"Socorro"},
{nombre:"Suaita"},
{nombre:"Sucre"},
{nombre:"Suratá"},
{nombre:"Tona"},
{nombre:"Valle de San José"},
{nombre:"Vélez"},
{nombre:"Vetas"},
{nombre:"Villanueva"},
{nombre:"Zapatoca"},
{nombre:"Sincelejo"},
{nombre:"Buenavista"},
{nombre:"Caimito"},
{nombre:"Coloso (Ricaurte)"},
{nombre:"Corozal"},
{nombre:"Chalán"},
{nombre:"Galeras (Nueva Granada)"},
{nombre:"Guarandá"},
{nombre:"La Unión"},
{nombre:"Los Palmitos"},
{nombre:"Majagual"},
{nombre:"Morroa"},
{nombre:"Ovejas"},
{nombre:"Palmito"},
{nombre:"Sampués"},
{nombre:"San Benito Abad"},
{nombre:"San Juan de Betulia"},
{nombre:"San Marcos"},
{nombre:"San Onofre"},
{nombre:"San Pedro"},
{nombre:"Sincé"},
{nombre:"Sucre"},
{nombre:"Tolú"},
{nombre:"Toluviejo"},
{nombre:"Ibagué"},
{nombre:"Alpujarra"},
{nombre:"Alvarado"},
{nombre:"Ambalema"},
{nombre:"Anzóategui"},
{nombre:"Armero (Guayabal)"},
{nombre:"Ataco"},
{nombre:"Cajamarca"},
{nombre:"Carmen de Apicalá"},
{nombre:"Casabianca"},
{nombre:"Chaparral"},
{nombre:"Coello"},
{nombre:"Coyaima"},
{nombre:"Cunday"},
{nombre:"Dolores"},
{nombre:"Espinal"},
{nombre:"Falán"},
{nombre:"Flandes"},
{nombre:"Fresno"},
{nombre:"Guamo"},
{nombre:"Herveo"},
{nombre:"Honda"},
{nombre:"Icononzo"},
{nombre:"Lérida"},
{nombre:"Líbano"},
{nombre:"Mariquita"},
{nombre:"Melgar"},
{nombre:"Murillo"},
{nombre:"Natagaima"},
{nombre:"Ortega"},
{nombre:"Palocabildo"},
{nombre:"Piedras"},
{nombre:"Planadas"},
{nombre:"Prado"},
{nombre:"Purificación"},
{nombre:"Rioblanco"},
{nombre:"Roncesvalles"},
{nombre:"Rovira"},
{nombre:"Saldaña"},
{nombre:"San Antonio"},
{nombre:"San Luis"},
{nombre:"Santa Isabel"},
{nombre:"Suárez"},
{nombre:"Zaragoza"},
{nombre:"Venadillo"},
{nombre:"Villahermosa"},
{nombre:"Villarrica"},
{nombre:"Cali"},
{nombre:"Alcalá"},
{nombre:"Andalucía"},
{nombre:"Ansermanuevo"},
{nombre:"Argelia"},
{nombre:"Bolívar"},
{nombre:"Buenaventura"},
{nombre:"Buga"},
{nombre:"Bugalagrande"},
{nombre:"Caicedonia"},
{nombre:"Calima (Darién)"},
{nombre:"Candelaria"},
{nombre:"Cartago"},
{nombre:"Dagua"},
{nombre:"El Águila"},
{nombre:"El Cairo"},
{nombre:"El Cerrito"},
{nombre:"El Dovio"},
{nombre:"Florida"},
{nombre:"Ginebra"},
{nombre:"Guacarí"},
{nombre:"Jamundí"},
{nombre:"La Cumbre"},
{nombre:"La Unión"},
{nombre:"La Victoria"},
{nombre:"Obando"},
{nombre:"Palmira"},
{nombre:"Pradera"},
{nombre:"Restrepo"},
{nombre:"Riofrío"},
{nombre:"Roldanillo"},
{nombre:"San Pedro"},
{nombre:"Sevilla"},
{nombre:"Toro"},
{nombre:"Trujillo"},
{nombre:"Tuluá"},
{nombre:"Ulloa"},
{nombre:"Versalles"},
{nombre:"Vijes"},
{nombre:"Yotoco"},
{nombre:"Yumbo"},
{nombre:"Zarzal"},
{nombre:"Mitú"},
{nombre:"Vaupés "},
{nombre:"Carurú"},
{nombre:"Tatamá"},
{nombre:"Vichada"},
{nombre:"Puerto Carreño"},
{nombre:"La Primavera"},
{nombre:"Santa Rosalia"},
{nombre:"Cumaribo"}]

municipios.each do |municipio|
	     			Municipio.where(municipio).first_or_create 
	   			end


departamentos=[{nombre:"Amazonas"},{nombre:"Antioquia"},{nombre:"Arauca"},{nombre:"Atlantico"},
	{nombre:"Bolivar"},{nombre:"Boyacá"},{nombre:"Caldas"},{nombre:"Caqueta"},{nombre:"Casanare"},
	{nombre:"Cauca"},{nombre:"Cesar"},{nombre:"Chocó"},{nombre:"Cordoba"},{nombre:"Cundinamarca"},
	{nombre:"Guainia"},{nombre:"Huila"},{nombre:"la Guajira"},{nombre:"Magdalena"},{nombre:"Meta"},
	{nombre:"Nariño"},{nombre:"norte de Santander"},{nombre:"Putumayo"},{nombre:"Quindío"},{nombre:"Risaralda"},
	{nombre:"san Andrés y Providencia"},{nombre:"Santander"},{nombre:"Sucre"},{nombre:"Tolima"},
	{nombre:"Valle del Cauca"},{nombre:"Vaupés"},{nombre:"Vichada"} ]
	
departamentos.each do |departamento|

	Departamento.where(departamento).first_or_create
end

tipoaccidentes=[{nombre:"Leve"},{nombre:"Grave"},{nombre:"Mortal"},{nombre:"In Itinere"},{nombre:"Con Baja"},
{nombre:"Sin Baja"}]

tipoaccidentes.each do |tipoaccidente|
	Tipoaccidente.where(tipoaccidente).first_or_create
end
